### ISSUE TITLE
Checklist to audit victory components with type definitions

### ISSUE THREAD

**Issue by wsparsons** [FormidableLabs/victory#1516]
# Feature Requests

### Checklist

- [x] Victory-Area (#1534)
- [x] Victory-Axis (#1527)
- [x] Victory-Bar (#1526)
- [x] Victory-Box-Plot (#1508)
- [x] Victory-Brush-Container (#1522)
- [x] Victory-Brush-Line (#1515)
- [x] Victory-Candlestick (#1512)
- [x] Victory-Chart (#1529)
- [x] Victory-Create-Container (no changes needed)
- [x] Victory-Cursor-Container (#1532)
- [x] Victory-Errorbar (#1528)
- [x] Victory-Group (#1554)
- [x] Victory-Legend (#1519)
- [x] Victory-Line (#1535)
- [x] Victory-Pie (#1538)
- [x] Victory-Polar-Axis (#1524)
- [x] Victory-Scatter (#1510)
- [x] Victory-Selection-Container (#1530)
- [x] Victory-Shared-Events (#1520)
- [x] Victory-Stack (#1543)
- [x] Victory-Tooltip (#1533)
- [x] Victory-Voronoi~ (#1514)
- [x] Victory-Voronoi-Container (#1521)
- [x] Victory-Zoom-Container (#1536)
