### ISSUE TITLE
Chore: Migrate packages to TypeScript

### ISSUE THREAD

**Issue by scottrippey** [FormidableLabs/victory#2318]
# Prerequisites
- [x] Support TypeScript in builds, tools, etc
- [x] Migrate `victory-core` and `victory-vendor` to TS

# Motivation
Migrating all other packages to TypeScript will have the following benefits:
- Type-safety for these packages, obviously
- Once we reach 100%, we can drop `babel` and use `tsc` directly

# Components to migrate
- [x] `victory` #2319
- [x] `victory-area` #2314 
- [x] `victory-axis` #2379 
- [x] `victory-bar` #2709
- [x] `victory-box-plot` #2387 
- [x] `victory-brush-container` #2393
- [x] `victory-brush-line` #2393
- [x] `victory-candlestick` #2716
- [x] `victory-canvas` #2710
- [x] `victory-chart` #2314
- [x] `victory-create-container` #2731 
- [x] `victory-cursor-container` #2419 
- [x] `victory-errorbar` 
- [x] `victory-group` #2396
- [x] `victory-histogram` #2719
- [x] `victory-legend` #2712
- [x] `victory-line` #2306 
- [x] `victory-native` #2739 
- [x] `victory-pie` #2740 
- [x] `victory-polar-axis`  #2713
- [x] `victory-scatter` #2394
- [x] `victory-selection-container` #2706
- [x] `victory-shared-events` #2733 
- [x] `victory-stack` #2422
- [x] `victory-tooltip` #2725
- [x] `victory-voronoi` #2726
- [x] `victory-voronoi-container` #2727 
- [x] `victory-zoom-container` #2730
